spring:
  application:
    name: blog
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      driver-class-name: org.postgresql.Driver
      clean-disabled: false
server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  signerKey: ${JWT_SIGNERKEY}
  valid-duration: ${VALID_DURATION}
  refreshable-duration: ${REFRESHABLE_DURATION}
admin:
  password: ${ADMIN_PASSWORD}
